create database ministerio_salud;

-- Tabla a publicar con registro de pacientes
-- DROP table pacientes;
create table pacientes
(
	id 	   int generated by default as identity(start with 1 increment by 1),
	nombre varchar(50) not null,
	cedula int not null,
	edad   int not null,
	vacuna int null,
	primary key(id)
);

create table vacuna_aplicada(
	id_vacuna    int generated by default as identity(start with 1 increment by 1),
	fecha 	     timestamp not null,
	id_paciente  int not null,
	primary key(id_vacuna, id_paciente),		
	foreign key (id_paciente) references pacientes
);

create table local_comercial(
	id_local       		   int generated by default as identity(start with 1 increment by 1),
	codigo_seguro          int not null,
	agente_ministrio_salud varchar(50) not null,
	local_name 	           varchar(50) not null,
	direccion	           varchar(100) not null
);


create role rol_proyecto3 with replication login password 'Proye3Ins';

grant all privileges on database ministerio_salud to rol_proyecto3;
grant all privileges on all tables in schema public to rol_proyecto3;

create publication mypub_pacientes
	for table public.pacientes
	WITH (publish = 'insert,update');

create publication mypub_vacuna
	for table public.mypub_vacuna_aplicada
	WITH (publish = 'insert,update');
